apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: rook-ceph
  namespace: rook-ceph
  includeCRDs: true
  releaseName: rook-ceph
  version: 1.15.1
  repo: https://charts.rook.io/release
#  additionalValuesFiles:
#  - manifests/rook-ceph-operator.values.yaml

- name: rook-ceph-cluster
  namespace: rook-ceph
  includeCRDs: true
  releaseName: rook-ceph-cluster
  version: 1.15.1
  repo: https://charts.rook.io/release
  additionalValuesFiles:
  - manifests/rook-ceph-cluster.values.yaml


resources:
- manifests/rook-ceph.namespace.yaml
- manifests/rook-ceph-dashboard.ingressroute.yaml
