apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#namespace: argo-cd

helmCharts:
- name: argo-cd
  namespace: argo-cd
  includeCRDs: true
  releaseName: argocd
  version: 7.5.2
  repo: https://argoproj.github.io/argo-helm
  valuesFile: values.yaml

patches:
- target:
    kind: ConfigMap
    name: argocd-cm
  patch: |-
    - op: add
      path: /data/kustomize.buildOptions
      value: --enable-helm

resources:
- manifests/argocd.namespace.yaml
- manifests/argocd.nodeport.yaml
- manifests/argocd.ingressroute.yaml
