apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: metallb
  includeCRDs: true
  releaseName: metallb
  version: 0.14.8
  repo: https://metallb.github.io/metallb
  valuesFile: values.yaml

resources:
- manifests/metallb-system.ipaddress-pool.k8s-home.yaml
- manifests/metallb-system.l2advertisement.k8s-home.yaml
