apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system

helmCharts:
- name: metallb
  includeCRDs: true
  releaseName: metallb
  version: 0.14.8
  repo: https://metallb.github.io/metallb
  valuesFile: values.yaml

resources:
- manifests/metallb.ipaddress-pool.k8s-home.yaml
- manifests/metallb.l2advertisement.k8s-home.yaml
