apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: traefik
  includeCRDs: true
  releaseName: traefik
  version: 31.0.0
  repo: https://traefik.github.io/charts
  additionalValuesFiles:
  - values.additional.yaml

patches:
- target:
    Kind: Deployment
    name: traefik
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-1
      value: "--serverstransport.insecureskipverify=true"
 
