apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: argo-cd
  includeCRDs: true
  releaseName: argo-cd
  version: 7.5.2
  repo: https://argoproj.github.io/argo-helm
  valuesFile: values.yaml

patches:
  - target:
      kind: ConfigMap
      name: argocd-cm
    patch: |-
      - op: add
        path: /data/kustomize.buildOptions
        value: --enable-helm
